name: .NET

on:
    push:
        branches: [ main ]

env:
    config: Release
    disable_test_parallelization: true

jobs:
    build:

        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:

            - name: Setup .NET 7
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 7.0.x

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Build Version
              run: |
                  dotnet tool install --global minver-cli --version 4.2.0
                  version=$(minver --tag-prefix v)
                  echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
                  echo "### Version: $version" >> $GITHUB_STEP_SUMMARY

            - name: Test
              run: ./build.sh --no-color ci
